#.
#.             ColoredTags by Filoghost
#.
#. This is the main configuration of the plugin.
#. Website: http://dev.bukkit.org/bukkit-plugins/colored-tags
#.
change-tab-names: true
update-notification: true
fix-death-messages: true
refresh-every-minute: true