Enable:
  playervsplayer: flase
  horse_killing_on_roads: true
  mob_killing_on_roads: true
  bestride_horse_on_roads: true
  monster_killing_everywhere: true
messages:
  event:
    nopvp: §c Voce nao pode matar os jogadores aqui!
    mobprotect: §c Voce nao pode matar os animais aqui!
    horseprotect: §c Voce nao pode matar cavalos aqui!
  cmd:
    info: '§7[PlotMeAnimals]§r Allowed Players:'
    added: §7[PlotMeAnimals]§a Jogador adicionado com sucesso.
    removed: §7[PlotMeAnimals]§a Jogador removido com sucesso.
    toofewarguments: §7[PlotMeAnimals]§c Too few arguments! /pa <arg> <name>
    notonplot: §7[PlotMeAnimals]§c Voce nao esta em um lote!
    notonlist: §7[PlotMeAnimals]§f Este jogador nao esta na lista.
    nolist: §7[PlotMeAnimals]§f Nenhum jogador foi adicionado ainda.
    nottheowner: §7[PlotMeAnimals]§c Esse nao e o seu lote!
